version: '3.8'

services:
  iris-app:
    image: iris-system
    container_name: iris_app
    ports:
      - 8080:8080
    depends_on:
      - db
    
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: irisdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwerty
 
    
